name: LevelChat
main: iJoshuaHD\LevelChat
version: 0.0.1
api: [1.13.0, 1.14.0, 2.0.0]
load: STARTUP
author: iJoshuaHD
description: A more dynamic manifold level chat.
website: https://github.com/LevelChat
